# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
#
# SPDX-License-Identifier: EUPL-1.2

---
default:
  image: node:22.15.0-alpine

stages:
  - analyze
  - lint
  - trigger
  - test
  - prepare-artifact
  - build
  - deploy
  - cleanup
  - e2e

.setup-pnpm: &setup-pnpm
  - npm install -g corepack@latest
  - corepack enable
  - |
    PNPM_VERSION=$(node -p "require('./package.json').packageManager.split('@')[1]")
    corepack prepare "pnpm@$PNPM_VERSION" --activate
  - pnpm config set store-dir .pnpm-store

.setup-e2e-tests: &setup-e2e-tests
  image: mcr.microsoft.com/playwright:v1.52.0-jammy
  stage: e2e
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  before_script:
    - *setup-pnpm
    - pnpm install

analyze:code_review:
  stage: analyze
  when: manual
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  before_script:
    - apk add --no-cache git
    - GIT_URL=https://gitlab-ci-token:${CI_JOB_TOKEN}@git.opentalk.dev/opentalk/tools/coreebo.git
    - git clone --depth 1 --branch $COREEBO_VERSION $GIT_URL
    - cd coreebo
    - npm ci
  script:
    - npm run review -- -id $CI_MERGE_REQUEST_IID

lint:prettier+eslint:
  stage: lint
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  before_script:
    - *setup-pnpm
  script:
    - pnpm install
    - pnpm lint
    - pnpm fmt:ci

lint:typecheck:
  stage: lint
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  before_script:
    - *setup-pnpm
  script:
    - pnpm install
    - pnpm typecheck
  allow_failure: true

lint:circular-deps:
  stage: lint
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  before_script:
    - *setup-pnpm
  script:
    - pnpm install
    - pnpm deps:circular

lint:yaml:
  stage: lint
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  before_script:
    - apk add --no-cache yamllint
  script: yamllint .

lint:compliance:
  stage: lint
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  before_script:
    - apk add --no-cache git
    - *setup-pnpm
    - pnpm install
  script:
    - pnpm licensee --production --errors-only

lint:licensing:
  stage: lint
  image:
    name: fsfe/reuse:5.0.2
    entrypoint: ['']
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  script:
    - reuse lint

lint:audit:
  stage: lint
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  before_script:
    - *setup-pnpm
  script:
    - pnpm audit --prod
  allow_failure: true

lint:commit:
  stage: lint
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  before_script:
    - apk add --no-cache git
    - npm install -g @commitlint/cli @commitlint/config-conventional
  script:
    - npx commitlint --from $CI_MERGE_REQUEST_DIFF_BASE_SHA --to HEAD --verbose

lint:unused-deps:
  stage: lint
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  before_script:
    - apk add --no-cache git
    - *setup-pnpm
    - pnpm install
  script:
    - pnpm knip --include dependencies

lint:unused-files:
  stage: lint
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  before_script:
    - apk add --no-cache git
    - *setup-pnpm
    - pnpm install
  script:
    - pnpm knip --include files

lint:commit-signature:
  stage: lint
  needs: []
  rules:
    # Run in merge requests only.
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  before_script:
    - apk add --no-cache git gnupg
  script:
    # %G? will log signature information for a commit. `N` stands for "no signature", `B` for "bad signature"
    # refer to https://git-scm.com/docs/pretty-formats#Documentation/pretty-formats.txt-emGem
    # grep checks that the output does not contain any "N" or "B" characters.
    - >
      git log --format=format:'%G?' $CI_MERGE_REQUEST_DIFF_BASE_SHA..HEAD
      | tr -d '\n'
      | grep -q -v -e "N" -e "B"

trigger_changelog_preview:
  stage: trigger
  needs: []
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  variables:
    # We need to hard code the target repository since the pipeline is running in the forked repository
    PIPELINE_PROJECT_PATH: opentalk/frontend/web/web-app
    PIPELINE_MERGE_REQUEST_PROJECT_PATH: $CI_MERGE_REQUEST_SOURCE_PROJECT_PATH
    PIPELINE_MERGE_REQUEST_SOURCE_BRANCH_NAME: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
    PIPELINE_MERGE_REQUEST_IID: $CI_MERGE_REQUEST_IID
  trigger: opentalk/tools/check-changelog

test:unit-tests:
  stage: test
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_TAG && $CI_PROJECT_ROOT_NAMESPACE == 'opentalk'
  before_script:
    - apk add --no-cache git
    - *setup-pnpm
    - pnpm install
  script:
    - pnpm test:unit:ci
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura-coverage.xml
      junit:
        - junit.xml
  coverage: /All files[^\|]*\|[^\|]*\s+([\d\.]+)/

prepare-artifact:build:
  stage: prepare-artifact
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_TAG && $CI_PROJECT_ROOT_NAMESPACE == 'opentalk'
  before_script:
    - apk add git jq
    - *setup-pnpm
    - pnpm install
  script:
    - pnpm build
    - echo v$(jq -r '.version' ./app/package.json) > ./dist/FRONTEND_VERSION
  artifacts:
    paths:
      - dist/*
    expire_in: 1 days

prepare-artifact:build-profiling:
  stage: prepare-artifact
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_TAG && $CI_PROJECT_ROOT_NAMESPACE == 'opentalk'
  before_script:
    - apk add git jq
    - *setup-pnpm
    - pnpm install
  script:
    - pnpm build:profiling
    - jq -r '.version' ./app/package.json > ./dist-profiling/FRONTEND_VERSION
  artifacts:
    paths:
      - dist-profiling/*
    expire_in: 1 days

# Upload Source Maps to our glitchtip instance when a tag is created and pushed to main
prepare-artifact:upload-sourcemaps:
  stage: prepare-artifact
  dependencies:
    - prepare-artifact:build
  needs:
    - prepare-artifact:build
  rules:
    - if: $CI_COMMIT_TAG && $CI_PROJECT_ROOT_NAMESPACE == 'opentalk'
  before_script:
    - *setup-pnpm
    - pnpm add -w @sentry/cli
    - echo "[ defaults ]" >> .sentryclirc
    - echo "url=${GLITCHTIP_URL}" >> .sentryclirc
    - echo "org=${GLITCHTIP_ORG}" >> .sentryclirc
    - echo "project=${GLITCHTIP_PROJECT}" >> .sentryclirc
  script:
    - RELEASE_TAG=${CI_COMMIT_TAG:-999.0.0-unreleased}
    - node_modules/.bin/sentry-cli sourcemaps inject dist/
    - node_modules/.bin/sentry-cli login --auth-token $GLITCHTIP_AUTH_TOKEN
    - node_modules/.bin/sentry-cli sourcemaps upload --release $RELEASE_TAG dist/
  artifacts:
    paths:
      - dist/*
    expire_in: 1 days

build:container:
  stage: build
  dependencies:
    - prepare-artifact:upload-sourcemaps
    - prepare-artifact:build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: ['']
  rules:
    # set variable for push to main
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      variables:
        IMAGE_DESTINATION_ARGS: --destination $CI_REGISTRY_IMAGE:latest
    # set variable for release tags
    - if: $CI_COMMIT_TAG && $CI_PROJECT_ROOT_NAMESPACE == 'opentalk'
      variables:
        IMAGE_DESTINATION_ARGS: >
          --destination $CI_REGISTRY_IMAGE:latest
          --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    # set variable for MR event
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      variables:
        IMAGE_DESTINATION_ARGS: >
          --destination ${CI_REGISTRY_IMAGE}:${CI_MERGE_REQUEST_IID}_${CI_COMMIT_REF_SLUG}
    # set variable for forked pipeline (commented out to get rid of pipelines in forked repos)
    # - if: $CI_PROJECT_ROOT_NAMESPACE != 'opentalk' &&
    #      $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH &&
    #      $CI_COMMIT_BRANCH != null
    #  variables:
    #    IMAGE_DESTINATION_ARGS: --no-push
  script:
    - mkdir -p /kaniko/.docker
    - >
      echo
      "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n ${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD} | base64)\"}}}" >
      /kaniko/.docker/config.json
    - >
      /kaniko/executor
      --registry-mirror=mirror.gcr.io
      --context $CI_PROJECT_DIR
      --dockerfile $CI_PROJECT_DIR/ci/Dockerfile
      $IMAGE_DESTINATION_ARGS
      --force
      --digest-file digest.txt
  artifacts:
    paths:
      - digest.txt
    expire_in: 1 days

build:container-profiling:
  stage: build
  dependencies:
    - prepare-artifact:build-profiling
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: ['']
  # todo - check when profiling should be build
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_TAG && $CI_PROJECT_ROOT_NAMESPACE == 'opentalk'
  script:
    - mkdir -p /kaniko/.docker
    - >
      echo
      "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n ${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD} | base64)\"}}}" >
      /kaniko/.docker/config.json
    - >
      /kaniko/executor
      --registry-mirror=mirror.gcr.io
      --context $CI_PROJECT_DIR
      --dockerfile $CI_PROJECT_DIR/ci/Dockerfile
      --destination $CI_REGISTRY_IMAGE:${CI_COMMIT_TAG:+$CI_COMMIT_TAG-}profiling
      --destination $CI_REGISTRY_IMAGE:profiling
      --build-arg DIST_FOLDER=dist-profiling
      --force
      --digest-file ./profiling-digest.txt

read-trivy-ignore-file:
  stage: build
  rules:
    - if: $CI_PIPELINE_SOURCE == 'schedule'
  script:
    - echo "TRIVY_IGNORE_STR=$(
         cat $CI_PROJECT_DIR/.trivyignore | sed -n 'H;${x;s/^\n//;s/\n/\\n/g;p}'
      )"  > package.env
  artifacts:
    reports:
      dotenv: package.env

container-scanning:
  needs:
    - build:container
    - read-trivy-ignore-file
  rules:
    - if: $CI_PIPELINE_SOURCE == 'schedule'
  stage: build
  variables:
    PIPELINE_FULL_IMAGE_NAME: $CI_REGISTRY_IMAGE:latest
    PIPELINE_PROJECT_WITH_NAMESPACE: $CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME
    PIPELINE_ADDITIONAL_LABELS: Frontend::Web App
    PIPELINE_TRIVY_IGNORE_FILE_STR_VAR: TRIVY_IGNORE_STR
  trigger:
    project: opentalk/opentalk-devops/scan-container
    strategy: depend
    forward:
      pipeline_variables: true

deploy:review-app:
  stage: deploy
  dependencies:
    - build:container
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  image: alpine/helm:3.17.3
  tags:
    - kubernetes
  before_script:
    - helm repo add --username gitlab-ci-token --password ${CI_JOB_TOKEN}
      opentalk https://git.opentalk.dev/api/v4/projects/649/packages/helm/testing
  script:
    - DIGEST=$(cat "./digest.txt")
    - helm uninstall frontend-$CI_MERGE_REQUEST_IID -n review-latest || true
    - >
      helm upgrade --version 3.1.3 --install --force frontend-$CI_MERGE_REQUEST_IID opentalk/opentalk-helm
      --set tags.standard=false
      --set tags.webapp=true
      --set webapp.image.pullPolicy=IfNotPresent
      --set webapp.image.registry=$CI_REGISTRY
      --set webapp.image.repository=$CI_PROJECT_PATH
      --set webapp.image.tag="@$DIGEST"
      --set webapp.imagePullSecrets[0].name=git
      --set 'webapp.ingress.annotations.kubernetes\.io/tls-acme=null'
      --set 'webapp.ingress.annotations.cert-manager\.io/cluster-issuer=null'
      --set webapp.ingress.enabled=true
      --set webapp.ingress.className=traefik
      --set webapp.ingress.tls[0].secretNameOverride=review-latest-tls
      --set global.defaultWebServiceProtocol=https
      --set global.webapp.domain=$CI_MERGE_REQUEST_IID.review-latest.kube.opentalk.run
      --set global.oidc.baseUrl=https://accounts.review-latest.kube.opentalk.run/auth
      --set global.oidc.realm=opentalk
      --set global.oidc.webapp.clientId=Webapp
      --set global.backend.domain=controller.review-latest.kube.opentalk.run
      --set webapp.ndtDomain=ndt.mailbox.org
      --set webapp.errorReportDomain=opentalk.eu
      --set webapp.feature.sharedFolder="true"
      --set webapp.imprintUrl=https://opentalk.eu/en/terms-of-use
      --set webapp.dataProtectionUrl=https://opentalk.eu/en/data-protection
      --set webapp.helpdeskUrl=https://opentalk.eu/docs/user/
      --set webapp.contactSupportUrl=https://opentalk.eu/en/contact-our-support-team
      --set webapp.sentryDsn=$SENTRY_DSN_TESTING
      --set webapp.livekit.domain=livekit.review-latest.kube.opentalk.run
      --set-string
      'webapp.ingress.annotations.traefik\.ingress\.kubernetes\.io/router\.middlewares=review-latest-auth@kubernetescrd'
      -n review-latest --wait
    - echo "https://${BASIC_AUTH_USER}:${BASIC_AUTH_PASS}@${CI_MERGE_REQUEST_IID}.review-latest.kube.opentalk.run"

e2e:chrome:
  <<: *setup-e2e-tests
  variables:
    INSTANCE_URL: https://${BASIC_AUTH_USER}:${BASIC_AUTH_PASS}@${CI_MERGE_REQUEST_IID}.review-latest.kube.opentalk.run
    USERNAME: ${E2E_CHROME_TEST_USERNAME}
    USER_EMAIL: ${E2E_CHROME_TEST_USER_EMAIL}
    PASSWORD: ${E2E_CHROME_TEST_USER_PASSWORD}
  script:
    - npx playwright install --with-deps
    - npx playwright test --project=chromium
  artifacts:
    when: always
    paths:
      - test-results/**/*.zip
    expire_in: 7 days

e2e:firefox:
  <<: *setup-e2e-tests
  # must be delete after tests are fixed
  when: manual
  variables:
    INSTANCE_URL: https://${BASIC_AUTH_USER}:${BASIC_AUTH_PASS}@${CI_MERGE_REQUEST_IID}.review-latest.kube.opentalk.run
    USERNAME: ${E2E_FIREFOX_TEST_USERNAME}
    USER_EMAIL: ${E2E_FIREFOX_TEST_USER_EMAIL}
    PASSWORD: ${E2E_FIREFOX_TEST_USER_PASSWORD}
  script:
    - npx playwright install --with-deps
    - npx playwright test --project=firefox
  artifacts:
    when: always
    paths:
      - test-results/**/*.zip
    expire_in: 7 days

e2e:webkit:
  <<: *setup-e2e-tests
  variables:
    INSTANCE_URL: https://${BASIC_AUTH_USER}:${BASIC_AUTH_PASS}@${CI_MERGE_REQUEST_IID}.review-latest.kube.opentalk.run
    USERNAME: ${E2E_WEBKIT_TEST_USERNAME}
    USER_EMAIL: ${E2E_WEBKIT_TEST_USER_EMAIL}
    PASSWORD: ${E2E_WEBKIT_TEST_USER_PASSWORD}
  script:
    - npx playwright install --with-deps
    - npx playwright test --project=webkit
  artifacts:
    when: always
    paths:
      - test-results/**/*.zip
    expire_in: 7 days

cleanup:review-app:
  stage: cleanup
  rules:
    - if: $CI_MERGE_REQUEST_EVENT_TYPE == "close"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH &&
        $CI_PROJECT_ROOT_NAMESPACE == 'opentalk' &&
        $CI_PIPELINE_SOURCE == 'push'
  allow_failure: true
  image:
    name: alpine/helm:3.17.3
    entrypoint: ['']
  tags:
    - kubernetes
  before_script:
    - apk add --no-cache --update curl
    - apk add --no-cache jq
    - apk add --no-cache kubectl
  script:
    - API_MR_URL="${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/merge_requests"
    - |
      MERGE_REQUEST_IID=`curl --header "PRIVATE-TOKEN: ${READ_API_TOKEN}" "${API_MR_URL}?scope=all&state=merged" | \
      jq --arg COMMIT_SHA $CI_COMMIT_SHA '.[] | select(.merge_commit_sha == $COMMIT_SHA).iid'`
    - echo $MERGE_REQUEST_IID
    - echo $CI_MERGE_REQUEST_IID
    - helm uninstall frontend-$MERGE_REQUEST_IID -n review-latest
    - kubectl delete secret frontend-$MERGE_REQUEST_IID-tls -n review-latest
