module.exports = {
  verbose: true,
  maxWorkers: '50%',
  coverageReporters: ['cobertura', 'lcov', 'json', 'text'],
  reporters: ['default', 'jest-junit'],
  collectCoverageFrom: [
    'packages/**/*.{ts,js,jsx,tsx}',
    'app/**/*.{ts,js,jsx,tsx}',
    '!packages/notistack/**',
    '!**/node_modules/**',
    '!**/assets/**',
    '!**/types/**',
    '!**/dist/**',
    '!**/build/**',
    '!**/public/**',
    '!**/devPublic/**',
    '!**/tests/**',
    '!**/test/**',
    '!**/example/**',
    '!**/stories/**',
    '!**/hotReload/**',
    '!**/coverage/**',
    '!**/__tests__/**',
    '!**/*.test.*',
    '!**/*.d.ts',
    '!**/setupTests.{ts,js}',
    '!**/.eslintrc.{ts,js,cjs}',
    '!**/babel.config.cjs',
    '!**/rollup.config.js',
    '!**/banner.js',
    '!**/tsHelper.ts',
    '!**/setupProxy.ts',
    '!**/reportWebVitals.ts',
    '!**/glitchtip.ts',
  ],
  projects: [
    {
      displayName: 'app',
      testEnvironment: 'jsdom',
      roots: ['<rootDir>/app/src'],
      setupFiles: ['<rootDir>/jest.config.js'],
      setupFilesAfterEnv: ['<rootDir>/app/src/setupTests.ts'],
      testMatch: ['<rootDir>/app/src/**/?(*.)+(spec|test).[jt]s?(x)'],
      modulePathIgnorePatterns: ['<rootDir>/packages/*'],
      moduleDirectories: ['node_modules', '../app/node_modules'],
      moduleNameMapper: {
        '\\.(png|jpg|webp|ttf|woff|woff2|mp4)$': '<rootDir>/mocks/fileMock.js',
        '\\.svg\\?react$': '<rootDir>/mocks/svgrMock.js',
        '@mui/styled-engine': '<rootDir>/node_modules/@mui/styled-engine',
        '^(camelcase-keys)$': '<rootDir>/mocks/camelcase-keys.js',
      },
      modulePaths: [],
      transformIgnorePatterns: ['/node_modules/(?!@heinlein-video/rrule*)'],
      resetMocks: true,
    },
    {
      displayName: 'packages/fluent_conv',
      testEnvironment: 'jsdom',
      testMatch: ['<rootDir>/packages/fluent_conv/**/?(*.)+(spec|test).[jt]s?(x)'],
    },
    {
      displayName: 'packages/i18next-fluent',
      testEnvironment: 'jsdom',
      testMatch: ['<rootDir>/packages/i18next-fluent/**/?(*.)+(spec|test).[jt]s?(x)'],
    },
    {
      displayName: 'packages/redux-oidc',
      testEnvironment: 'jsdom',
      testMatch: ['<rootDir>/packages/redux-oidc/**/?(*.)+(spec|test).[jt]s?(x)'],
    },
    {
      displayName: 'packages/rtk-rest-api',
      testEnvironment: 'jsdom',
      setupFilesAfterEnv: ['./packages/rtk-rest-api/src/setupTests.js'],
      testMatch: ['<rootDir>/packages/rtk-rest-api/**/?(*.)+(spec|test).[jt]s?(x)'],
      moduleNameMapper: {
        '^(camelcase-keys)$': '<rootDir>/mocks/camelcase-keys.js',
      },
    },
  ],
};
