# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
#
# SPDX-License-Identifier: EUPL-1.2

---
packages:
  - app
  - packages/*

onlyBuiltDependencies:
  - msw

# can be removed when the following issue with tinypool is resolved:
# https://github.com/vitest-dev/vitest/issues/8201
overrides:
  "vitest>tinypool": 1.0.2
